### ISSUE TITLE
Frontend updates

### ISSUE THREAD

**Issue by rajamazumder** [biocompute-objects/portal#114]
AT
https://biocomputeobject.org/account
ADD
Tooltips for BioCompute Object Servers
PRIORITY CRITICAL

AT
https://biocomputeobject.org/objects
ADD
Simple text search for searching with min BCO ID
PRIORITY MEDIUM

REMOVE FILTER on page. PRIORITY MEDIUM.

AT
https://biocomputeobject.org/objects/view/https/biocomputeobject.org/ARGOS_000014/1.2
CHANGE
Object Tools 
TO
EDIT OBJECT big button.

**Comment by HadleyKing** [comment]
- [ ] AT https://biocomputeobject.org/account ADD Tooltips for BioCompute Object Servers PRIORITY CRITICAL

- [ ] AT https://biocomputeobject.org/objects ADD Simple text search for searching with min BCO ID PRIORITY MEDIUM

- [ ] REMOVE FILTER on [Object view](https://biocomputeobject.org/objects) page. PRIORITY MEDIUM.

- [ ]  AT https://biocomputeobject.org/objects/view/https/biocomputeobject.org/ARGOS_000014/1.2 CHANGE Object Tools TO EDIT OBJECT big button.
