### ISSUE TITLE
Registration is failing

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/portal#117]
A few issues
- [x] [CSRF Failed: CSRF token missing or incorrect](https://stackoverflow.com/questions/26639169/csrf-failed-csrf-token-missing-or-incorrect) if someone has cookies
- [x] Alert Messaging is not correct for registration (see #118 )

**Comment by HadleyKing** [comment]
769a407471a7defc4a3f2788f4a6700f7d8f5ac2

**Comment by jpat1546** [comment]
Addressed and fixed in test 👍
