### ISSUE TITLE
Raw version of BCO editor not editable

### ISSUE THREAD

**Issue by CollectorsCorner** [biocompute-objects/portal#12]
Only the color coded version of the BCO editor is loading. The raw version that loaded yesterday is down.

**Comment by jpat1546** [comment]
Original issue addressed (now loads), h/e user unable to edit raw json in builder.

**Comment by jpat1546** [comment]
Est: unknown - 1-5hrs

**Comment by syntheticgio** [comment]
Looks like this is fixed?  I appear to be able to edit the raw JSON when creating an object - maybe there is more to it than that?  @HadleyKing ?

**Comment by HadleyKing** [comment]
IT is working but there are still some small bugs. I think we may need to remove the local storage feature for the time being. It will simplify everything else.

**Comment by HadleyKing** [comment]
https://github.com/biocompute-objects/portal/commit/c89ed2803968ff96332264ec7267086a1646ae4a
