### ISSUE TITLE
Download a complete BCO draft saves an empty file

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/portal#123]
<img width="894" alt="image" src="https://user-images.githubusercontent.com/23385872/157277340-fce2b7dd-d201-4787-af02-c1c72c2721cd.png">
<img width="715" alt="image" src="https://user-images.githubusercontent.com/23385872/157277458-5aaf1860-7791-45bb-8c87-3416b00dbf26.png">

**Comment by burakturkoglu5454** [comment]
null

**Comment by jpat1546** [comment]
Replicated (partially?)--> saved incomplete draft---> [#92](https://github.com/biocompute-objects/bco_api/issues/92)
