### ISSUE TITLE
Add RO-Crate paper to https://biocomputeobject.org/resources

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/portal#127]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by stain** [comment]
Stian Soiland-Reyes, Peter Sefton, Mercè Crosas, Leyla Jael Castro, Frederik Coppens, José M. Fernández, Daniel Garijo, Björn Grüning, Marco La Rosa, Simone Leo, Eoghan Ó Carragáin, Marc Portier, Ana Trisovic, RO-Crate Community, Paul Groth, Carole Goble (2022):
Packaging research artefacts with RO-Crate.
Data Science (in press).
https://doi.org/10.3233/DS-210053

**Comment by jpat1546** [comment]
@HadleyKing added the RO-Crate paper into the website, so closing this issue.  
Opening a separate publications issue because this does bring up how we’d like to organize BCO focused papers v citations…. Maybe we categorize all publications by "Core BioCompute Publications" and "BCO Citations".
