### ISSUE TITLE
Copy and paste feature is enabled in some fields but not others

### ISSUE THREAD

**Issue by CollectorsCorner** [biocompute-objects/portal#13]
Users can C&P in name and license but not in versions and this continues on throughout the builder.

**Comment by carmstrong1gw** [comment]
This may be unavoidable as some fields are using regular expressions to check the inputs and therefore a bulk copy and paste may not satisfy the constraints leading to a blank field.

**Comment by jpat1546** [comment]
Given constraints, not able to fix for 4.0.0 milestone. Will be discussed at a later date. 
Indicate which sections allow for C+P
