### ISSUE TITLE
Publications on biocomputeobject.org

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/portal#132]
how we’d like to organize BCO focused papers v citations…. Maybe we categorize all publications by "Core BioCompute Publications" and "BCO Citations".

**Comment by HadleyKing** [comment]
Maybe this is a good agenda Item for next week's TSC?

**Comment by jpat1546** [comment]
Proposed changes:

Core BCO Publications
- King CH, Keeney J, Guimera N, Das S, Weber M, Fochtman B, Walderhaug MO, Talwar S, Patel JA, Mazumder R, Donaldson EF. Communicating regulatory high-throughput sequencing data using BioCompute Objects. Drug Discov Today. 2022 Jan 22; PMID: [35077912](https://pubmed.ncbi.nlm.nih.gov/35077912/).
- Patel JA, Dean DA, King CH, Xiao N, Koc S, Minina E, Golikov A, Brooks P, Kahsay R, Navelkar R, Ray M, Roberson D, Armstrong C, Mazumder R, Keeney J.
- Bioinformatics tools developed to support BioCompute Objects. Database (Oxford).2021 March 31; PMID:[33784373](https://pubmed.ncbi.nlm.nih.gov/33784373/).
- Alterovitz G, Dean D A, Goble C, Crusoe M R, Soiland-Reyes S, Bell A, Hayes A, King, C H S, Taylor D, Johanson E, Thompson E E, Donaldson E, Morizono H, Tsang H S, Goecks J, Yao J, Almeida J S, Krampis K, Guo L, Walderhaug M, Walsh P, Kahsay R, Gottipati S, Bloom T, Lai Y, Simonyan V, Mazumder R. Enabling Precision Medicine via standard communication of HTS provenance, analysis, and results. PLOS Biology; 16(12): e3000099.2018.[ https://doi.org/10.1371/journal.pbio.3000099](https://doi.org/10.1371/journal.pbio.3000099)
- Simonyan V, Goecks J, Mazumder R. BioCompute objects - a step towards evaluation and validation of bio-medical scientific computations. PDA J Pharm Sci Technol. 2017;71(2):136-146 PMID:[27974626](https://www.ncbi.nlm.nih.gov/pubmed/27974626).

BCO Citations
Stian Soiland-Reyes, Peter Sefton, Mercè Crosas, Leyla Jael Castro, Frederik Coppens, José M. Fernández, Daniel Garijo, Björn Grüning, Marco La Rosa, Simone Leo, Eoghan Ó Carragáin, Marc Portier, Ana Trisovic, RO-Crate Community, Paul Groth, Carole Goble. Packaging research artefacts with RO-Crate. Data Science, 2022;[ https://doi.org/10.3233/DS-210053](https://doi.org/10.3233/DS-210053).

**Comment by jpat1546** [comment]
Address at TSC, then reassign to HK for front end portal changes based on TSC discussion.

**Comment by HadleyKing** [comment]
@tiwa1154 
We should create a Publications page on the Wiki to take care of this issue. Then we can remove the static content from the biocomputeobject.org site.

**Comment by HadleyKing** [comment]
https://wiki.biocomputeobject.org/index.php?title=Publications
