### ISSUE TITLE
BCO step numbers change to zero

### ISSUE THREAD

**Issue by penningtonea** [biocompute-objects/portal#135]
# **Describe the bug**
*A clear and concise description of what the bug is.*

Step numbers added in the description domain section when using color coded view turn into zeros in tree view and in raw JSON view.  Ex: I type 1 in the box labeled "Step Number", reflects as step number int0 in tree view and step number 0 in raw JSON, 

# **To Reproduce**
*Steps to reproduce the behavior:*

1. Go to BCO builder. 
2. Fill in a non-zero number in the box labeled "Step Number" in the description domain. 
3. Save draft
4. Check draft in Tree view or raw JSON view
5. See error

# **Expected behavior**
The correct number for the appropriate step should be there. 

# **Screenshots**
![image](https://user-images.githubusercontent.com/70979519/163016337-015ff845-7a21-4258-825e-b28a651515a1.png)
![image](https://user-images.githubusercontent.com/70979519/163016447-b656c49c-6b13-44f3-a91c-d40c7eca1672.png)
![image](https://user-images.githubusercontent.com/70979519/163016498-960ccf45-38a8-47f4-ab88-55f51fb95252.png)

# **Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser  Chrome

# **Additional context**
N/A

**Comment by HadleyKing** [comment]
Fixed with https://github.com/biocompute-objects/portal/commit/feb4e2451ad92cf3f09bc9d9c4df52b8bf05d905
