### ISSUE TITLE
Access time error format in BCO

### ISSUE THREAD

**Issue by penningtonea** [biocompute-objects/portal#137]
# **Describe the bug**
When a draft is complete and the user clicks "Validate draft" an error message stating that the access time in the description domain does not match "date-time" format. I have received the same error message for multiple sections within the description domain, including when adding prerequisite information, input information, and output information. 

The error message reads:

You have an error in your format.
".description_domain.pipeline_steps[1].prerequisite[1].uri.access_time" should match format "date-time"

# **To Reproduce**
When drafting a BCO:
1. Fill out steps in the description domain 
2. In this example, a prerequisite filename and uri was added to step 1.
3. Finish filling out the information for that step.
4. Click "validate BCO"

# **Expected behavior**
The user should not have to fill out access time information when drafting or validating a BCO. 

![image](https://user-images.githubusercontent.com/70979519/163260550-4a4f6b06-e818-4174-bfac-b492b9391bce.png)

![image](https://user-images.githubusercontent.com/70979519/163260576-ba143ef4-98d1-440a-adb8-643bef11036e.png)

![image](https://user-images.githubusercontent.com/70979519/163261453-c48857cd-91b2-424f-85ab-8d95fc333854.png)

# **Desktop (please complete the following information):**

 - OS: Windows 
 - Browser: Chrome

# **Additional context**
The same error message also sometimes comes up relating to the checksum portion of the steps in the description domain.

**Comment by HadleyKing** [comment]
This is the result of the UI auto filling fields that are not required.

**Comment by HadleyKing** [comment]
This error should be resolved with the modifications to the validation fuinctions
