### ISSUE TITLE
Draft save error when changing Object ID

### ISSUE THREAD

**Issue by penningtonea** [biocompute-objects/portal#140]
# **Describe the bug**
Builder cannot save draft after the object ID has been manually edited in raw JSON viewer. Receive the error message: "Save Draft FAILED! Error: 300"

# **To Reproduce**
1) manually change the object ID of the draft in JSON viewer
2) Click "save current draft"
3) See error

# **Expected behavior**
Draft should save 

# **Screenshots**
![image](https://user-images.githubusercontent.com/70979519/163425186-3d9d07f3-3db1-462d-8796-e83f3741848d.png)

# **Desktop (please complete the following information):**

 - OS: Windows10
 - Browser  Chrome

# **Additional context**
N/A

**Comment by HadleyKing** [comment]
This issue stems from the fact that a BCOId is created by the API which throws an error when a user submitted BCO has an ID already. This will need some consideration on how the UI and API are interacting in this situation.

**Comment by HadleyKing** [comment]
<img width="457" alt="Screen Shot 2022-08-06 at 6 01 25 PM" src="https://user-images.githubusercontent.com/20343214/183267470-2803253f-99f1-453f-82f8-1fb7a5179c0b.png">
