### ISSUE TITLE
ISO date-time format error fix

### ISSUE THREAD

**Issue by penningtonea** [biocompute-objects/portal#157]
**Is your feature request related to a problem? Please describe.**
The provenance domain requires the date-time to be in accordance with ISO standards. BCO builder sends an error message when the format doesn't match with the ISO guidelines but does not specify the correct format. There is a line in the error message that details where the user can find the correct formatting but it does not link out to the site. 

**Describe the solution you'd like**
Provide instructions for the formatting in the color-code view section for the user to follow directly

**Describe alternatives you've considered**
Include a hyperlink to documentation for the correct formatting

**Additional context**

[provenance_domain_date-time_error.docx](https://github.com/biocompute-objects/portal/files/8673448/provenance_domain_date-time_error.docx)

**Comment by HadleyKing** [comment]
@penningtonea 
![image](https://user-images.githubusercontent.com/20343214/168111161-cad5052e-6a63-4d4d-86b1-a1ef0cf74cb3.png)

That is a very good idea: "make the bottom into a hyperlink", and I think it may doable in general. 

This issue would be solved by adding a date-time picker. As would #150
