### ISSUE TITLE
IO Domain Information Disappearing on Validation

### ISSUE THREAD

**Issue by kee007ney** [biocompute-objects/portal#158]
_Seems to have been an issue with two groups now. Account from one user is below._

I am very confident that I edited something in the IO Domain, and I successfully saved it. 
This situation I had one time before, that case is pretty similar, I made some mistakes in the IO Domain and then I clicked on the validated button, it erased all my info in that domain, and I need to re-do that part again with the right format.

Version 1.1 for biosample ( I can not save it with the IO Domain, so l listed here the info for your reference.)
https://biocomputeobject.org/builder/https/biocomputeobject.org/BCO_000128/DRAFT

**IO Domain information -** 
input: 
BioSample - NCBI
https://www.ncbi.nlm.nih.gov/biosample
output：
text/tsv
biosampleMeta_Crandall.tsv
http://data.argosdb.org/ln2data/crandalllab/biosampleMeta_Crandall.tsv

**Here is a scenario in that you could reproduce that problem:**
1. derive a draft from any published BCO
2. Make sure you enter something in the IO Domain, then click "save" and then "validated".

![image](https://user-images.githubusercontent.com/12193741/168091320-6179e5d5-af8e-4e51-b4d1-832ff075eda9.png)

4. After showing the error message if we had a mistake somewhere, we fixed the contributor part and click "save”, and "validated". For right now, we still have everything there.
5. Close the tab and re-open it from my BCOs, we could find that the IO Domain info was gone.

![image (1)](https://user-images.githubusercontent.com/12193741/168091317-dc236f99-8b2c-45cb-8d27-217fd6155028.png)

**Comment by HadleyKing** [comment]
This is most likely a “state” variable/local storage issue. We use both for the BCOs and some times they get mixed up.
