### ISSUE TITLE
Typos on Builder page

### ISSUE THREAD

**Issue by skeeney01** [biocompute-objects/portal#170]
# **Describe the bug**
*A clear and concise description of what the bug is.*

Multiple typos or grammar issues in Builder page. 

# **To Reproduce**
*Steps to reproduce the behavior:*

1. Go to Builder
2. Click on Saving and Publishing
3. Scroll down to Functions OR
4. Scroll down to Instructions
5. See typos 

# **Expected behavior**
*A clear and concise description of what you expected to happen.*

N/A

# **Screenshots**

Corrected typos/grammar:
-Moderate Priority
-Possible extra space between comma and “you” in error message from VALIDATE DRAFT button. 1) If this field is blank, you may need to delete it.
-Comma needed in error message from VALIDATE DRAFT button. 2) If this field appears correct, check for extra spaces. 
-Punctuation missing from DELETE DRAFT message. Are you sure you want to delete BCO_000000/DRAFT? 
-Punctuation missing and typo in DOWNLOAD DRAFT Instructions in Saving and Publishing. This will download a JSON of the current DRAFT.
-Unneeded space in DOWNLOAD DRAFT instruction step. 7) DOWNLOAD DRAFT.
-Capitalize Mediatype in Output Subdomain.

# **Desktop (please complete the following information):**

 - OS: macOS Monterey 12.0.1
 - Browser:  Safari

# **Additional context**

N/A

**Comment by HadleyKing** [comment]
Corrected typos/grammar:
- [ ] Moderate Priority 
- [ ] Possible extra space between comma and “you” in error message from VALIDATE DRAFT button. 1) If this field is blank, you may need to delete it. 
- [ ] Comma needed in error message from VALIDATE DRAFT button. 2) If this field appears correct, check for extra spaces.
- [ ] Punctuation missing from DELETE DRAFT message. Are you sure you want to delete BCO_000000/DRAFT? 
- [ ] Punctuation missing and typo in DOWNLOAD DRAFT Instructions in Saving and Publishing. This will download a JSON of the current DRAFT. 
- [ ] Unneeded space in DOWNLOAD DRAFT instruction step. 7) DOWNLOAD DRAFT. 
- [ ] Capitalize Mediatype in Output Subdomain.
