### ISSUE TITLE
Cannot delete published BCO

### ISSUE THREAD

**Issue by skeeney01** [biocompute-objects/portal#174]
**Is your feature request related to a problem? Please describe.**
Duplicate BCO Objects cannot be deleted.

**Describe the solution you'd like**
A function that will delete just one selected BCO object.

**Describe alternatives you've considered**
None.

**Additional context**
The etags for duplicate BCOs are identical, but time stamps differ, so they could be used to differentiate and delete unneeded BCOs.

**Comment by HadleyKing** [comment]
This was an issue with database content. It has been resolved
