### ISSUE TITLE
BCO Builder under Platform: “-” button

### ISSUE THREAD

**Issue by skeeney01** [biocompute-objects/portal#176]
# **Describe the bug**
In the Description Domain under 'Platform', removing a box with the “-” button did not work until the box to add another platform was typed into.

# **To Reproduce**
*Steps to reproduce the behavior:*

***[EXAMPLE STEP TEMPLATE BELOW: FILL IN INFO AND ADD/REMOVE STEPS AS NEEDED]***

1. Go to 'Builder'
2. Scroll to 'Description Domain'
3. Under 'Platform' type in the box and click the "+" button to add platform
4. Repeat Step 3 a few more times
5. Click on the "-" button to remove a platform
.6 Type into the add platform 

# **Expected behavior**
*A clear and concise description of what you expected to happen.*
Expected the correct platform box to be removed when I clicked on the associated "-" button.

# **Screenshots**

# **Desktop (please complete the following information):**

 - OS: macOS Monterey 12.0.1
 - Browser: Safari

# **Additional context**

The "-" button works, but not until the box to ADD a platform is typed into.

**Comment by HadleyKing** [comment]
Another state problem

**Comment by plam87** [comment]
Fix Commit: addd569a015dcd611aae97a4554e1aae79f0333e
Branch: 22.08
