### ISSUE TITLE
Save as you go button is required

### ISSUE THREAD

**Issue by CollectorsCorner** [biocompute-objects/portal#19]
Just got kicked out while working all afternoon on the BCO. There is no way to save as you go and retrieve the data. The Draft Sharing and Publishing is not sufficient nor intuitive.

**Comment by carmstrong1gw** [comment]
Expand on your explanation?

**Comment by CollectorsCorner** [comment]
When you are creating a BCO there should be an ability to save the BCO and the user can return later and complete the BCO. Right now that feature does not exist. Even the save draft feature requires you to draft the whole BCO before saving it.

**Comment by carmstrong1gw** [comment]
The save draft button is at the top under "DRAFT TOOLS".  You don't need to draft the whole BCO to save it.
