### ISSUE TITLE
BioCompute Documentation

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/portal#190]
# **Describe the bug**
*BioCompute Documentation directs to a different link than stated on the Portal Testing spreadsheet. It redirects to https://docs.biocomputeobject.org/ instead of https://portal.biochemistry.gwu.edu/documentation*

# **To Reproduce**
1. Go to https://test.portal.biochemistry.gwu.edu/
2. Click on BioCompute Documentation

# **Desktop (please complete the following information):**
macOS Monterey - Firefox

# **Additional context**
This could be a pre-existing issue. https://docs.biocomputeobject.org/  seems to have all the needed documentation. If the link has changed permanently, the instruction in the Portal Testing spreadsheet needs to be changed.

**Comment by HadleyKing** [comment]
Yes. This is a problem with the testing sheet no the site.
