### ISSUE TITLE
Multiple Step zeroes in pipeline steps

### ISSUE THREAD

**Issue by Rohanpanigrahi** [biocompute-objects/portal#198]
# **Describe the bug**
In the description domain, specifically pipeline steps, multiple step zeroes are generated. In the builder itself the steps appear as 1, 2, etc However, in the JSON both steps 1 and 2 appear as 0.  From step 3 and onward the steps count normally.  

# **To Reproduce**
*Steps to reproduce the behavior:*
1. Go down to description domain
2. Add step 2 
3. Check JSON for "step_number" 
4. View the step number indicated by JSON
5. Should show a 0 next to both steps 1 and 2

# **Expected behavior**
*A clear and concise description of what you expected to happen.*
What should happen is that at step 1 a 0 should appear. At step 2 a 1, etc. 

# **Screenshots**

![image](https://user-images.githubusercontent.com/108543227/176944453-a52f2b89-aaab-4e03-ab92-417f185a9648.png)
![image](https://user-images.githubusercontent.com/108543227/176944535-22db995f-e6d8-4cea-8698-aa700d353020.png)

# **Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser: Firefox

**Comment by HadleyKing** [comment]
This is another issue related to the state variable and updating the JSON in the local storage.

**Comment by HadleyKing** [comment]
This issues was resolved with https://github.com/biocompute-objects/portal/issues/135
