### ISSUE TITLE
Provenance Domain/modified - not able to type a modified date 

### ISSUE THREAD

**Issue by CollectorsCorner** [biocompute-objects/portal#20]
Not able to type in the modified date in the modified text box - my impression is that the dataset/workflow has been modified and not the BCO. The date that a BCO is being modified should be automatically generated. 
![image](https://user-images.githubusercontent.com/11906413/119736294-7f26b580-be4b-11eb-9167-2d44aac7f64c.png)

**Comment by carmstrong1gw** [comment]
We are a bit averse to automatic date generation unless something in the IEEE spec suggests we should use it for a given field.

**Comment by HadleyKing** [comment]
@CollectorsCorner,
This is a `FEATURE` not a `BUG`. The `modified` and `created` fields are auto-populated by the portal.
