### ISSUE TITLE
Report issue on GitHub goes to https://github.com/carmstrong1gw/portal/issues

### ISSUE THREAD

**Issue by CollectorsCorner** [biocompute-objects/portal#21]
I was provided https://github.com/biocompute-objects/portal/issues/ through slack and I should be able to access directly from the Biocompute Website

![image](https://user-images.githubusercontent.com/11906413/119736466-c01eca00-be4b-11eb-8afa-af15bdf1ec92.png)

**Comment by HadleyKing** [comment]
#9
