### ISSUE TITLE
Draft Sharing and Publishing - not sure what its function is

### ISSUE THREAD

**Issue by CollectorsCorner** [biocompute-objects/portal#22]
This feature is not very intuitive, there are three boxes to check but when the user clicks on one all of them are automatically selected. Also why can't I assign my own group? I would prefer it to be OncoMX instead of my username. 
![image](https://user-images.githubusercontent.com/11906413/119737610-89e24a00-be4d-11eb-90ee-70da4e9decdf.png)

**Comment by jpat1546** [comment]
Will be resolved by #23
