### ISSUE TITLE
Published BCOs show wrong step number

### ISSUE THREAD

**Issue by penningtonea** [biocompute-objects/portal#225]
# **Describe the bug**
The step numbers change when a BCO is published from the actual number to zero 

# **To Reproduce**
*Steps to reproduce the behavior:*

Checked with dataset API that the BCO's still have that little bug where the step numbers all revert to 0

***[EXAMPLE STEP TEMPLATE BELOW: FILL IN INFO AND ADD/REMOVE STEPS AS NEEDED]***

1. Go to ARGOS_000001 (for example)
3. Scroll down to description domain

# **Expected behavior**
Steps should be numbered correctly 

# **Desktop (please complete the following information):**

 - OS: Windows10]
 - Browser  Chome

**Comment by HadleyKing** [comment]
@penningtonea 
Thanks for the bug report but this is a `feature` not a bug! The `step numbers` are entered by the user.
