### ISSUE TITLE
I thought there was a "About" page which lists current and past folks.

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/portal#247]

**Comment by rajamazumder** [comment]
No. Something like this https://www.glygen.org/about/

**Comment by HadleyKing** [comment]
@rajamazumder I added this to planned work for [22.12](https://github.com/orgs/biocompute-objects/projects/11/views/1)

**Comment by tiwa1154** [comment]
@rajamazumder Here is a mock up:https://www.figma.com/file/jqfeR3RQgiqMp2shzr6VrU/Untitled?node-id=0%3A1&t=BH8ztGffWgnTOzHA-1

**Comment by rajamazumder** [comment]
Please implement

**Comment by HadleyKing** [comment]
Fixed with https://github.com/biocompute-objects/BCO_Specification/commit/920613a6d2edad6be94a4fd893280def6804ea81
