### ISSUE TITLE
Error Domain

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/portal#249]
# **Describe the bug**
As soon as starting typing in Error Domain, an error message shows up "SyntaxError: JSON.parse: expected property name or '}' at line 1 column 3 of the JSON data"

![Screen Shot 2022-10-25 at 15 47 45](https://user-images.githubusercontent.com/90009613/197868221-0c65675d-90c1-4cb6-833e-aed1c122ea23.png)

**Comment by HadleyKing** [comment]
This is a feature not a bug. If the JSON is valid the error will go away.
