### ISSUE TITLE
Username and password not working 

### ISSUE THREAD

**Issue by CollectorsCorner** [biocompute-objects/portal#25]
Can we adjust the code so that when an update is being made to the editor it does not wipe out username and password too?

**Comment by carmstrong1gw** [comment]
Yes, this should be working by 6/3.

**Comment by HadleyKing** [comment]
@carmstrong1gw this has been solved, correct? Please comment with commit and close if so.

**Comment by CollectorsCorner** [comment]
This has now been resolved and I can use the same login credentials that I've created.
