### ISSUE TITLE
GlyGen BCO ID is not sequential

### ISSUE THREAD

**Issue by jeet-vora** [biocompute-objects/portal#250]
# **When creating a new BCO from the builder, the builder assigns the BCO with ID based on the number of records eg[GLY_001063DRAFT](https://www.biocomputeobject.org/builder/https/biocomputeobject.org/GLY_001063/DRAFT). However, this is incorrect as it should have assigned an ID in the sequential order of the published datasets, GLY_000704 instead of GLY_001063**
*A clear and concise description of what the bug is.*

***[REPLACE WITH BUG DESCRIPTION]***

# **To Reproduce**
*Steps to reproduce the behavior:*

***[EXAMPLE STEP TEMPLATE BELOW: FILL IN INFO AND ADD/REMOVE STEPS AS NEEDED]***

# **Expected behavior**
*A clear and concise description of what you expected to happen.*

***[REPLACE WITH THE BEHAVIOR YOU EXPECTED. PUT N/A IF YOU ARE UNSURE.]***

# **Screenshots**

***
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/25825266/198064187-4664f20d-9b85-420e-b590-82380f922c67.png">
***

# **Desktop (please complete the following information):**

 - OS: ***[REPLACE WITH YOUR OPERATING SYSTEM: e.g. Windows10]***
 - Browser  ***[REPLACE WITH THE BROWSER YOU ACCESSED THE PORTAL ON: e.g. Chome, Firefox]***

# **Additional context**

***[ADD ANY ADDITONAL INFORMATION YOU FEEL WASN'T INCLUDED ABOVE. PUT N/A IF THERE IS NONE]***

**Comment by HadleyKing** [comment]
Fixed via BCO API DB
