### ISSUE TITLE
Unable to update information in ARGOS_000002 BCO

### ISSUE THREAD

**Issue by JingyueWu** [biocompute-objects/portal#253]
# **Describe the bug**
*A clear and concise description of what the bug is.*

Information in required fields is not saved after each update. 

# **To Reproduce**
*Steps to reproduce the behavior:*

***[EXAMPLE STEP TEMPLATE BELOW: FILL IN INFO AND ADD/REMOVE STEPS AS NEEDED]***

Example 1 -- 
1. Go to 'Extension Domain'
2. Scroll down to 'Extension Schema'
3. The second extension schema (i.e. ARGOS_000002 ExtDom.txt updated via the backend is not showing)

Example 2 -- 
1. Go to 'Usability Domain'
2. The updated title "Sudan Ebola genome assembly using MEGAHIT" is missing before the description paragraph 

Example 3 -- 
1. Go to 'IO Domain'
2. The updated file name and URI are not saved

# **Expected behavior**
*A clear and concise description of what you expected to happen.*

The above updated information that are missing need to be shown in this BCO, in order to proceed to final completion.

# **Screenshots**

***[PASTE IMAGE HERE. OPTIONALLY ADD DESCRIPTION]***

# **Desktop (please complete the following information):**

 - OS: macOS
 - Browser: Safari

# **Additional context**

***[ADD ANY ADDITONAL INFORMATION YOU FEEL WASN'T INCLUDED ABOVE. PUT N/A IF THERE IS NONE]***

**Comment by HadleyKing** [comment]
Fixed via UI
