### ISSUE TITLE
Unable to update information in ARG_000001 BCO

### ISSUE THREAD

**Issue by JingyueWu** [biocompute-objects/portal#258]
# **Describe the bug**
Information in required fields is not saved after each update in ARG_000001 BCO.

# **To Reproduce**
1. Go to 'IO Domain'
2. The updated file name and URI are not saved for 'Input Subdomain' 

# **Expected behavior**
The above updated information that are missing need to be shown in this BCO, in order to proceed to final completion.

# **Screenshots**

# **Desktop (please complete the following information):**

 - OS: MacOS
 - Browser  Safari

# **Additional context**
N/A

**Comment by HadleyKing** [comment]
Was not able to replicate issue
