### ISSUE TITLE
Unable to add new groups

### ISSUE THREAD

**Issue by acoleman2000** [biocompute-objects/portal#37]
# **Describe the bug**
*A clear and concise description of what the bug is.*

When I go to add groups on my account homepage the add group button doesn't do anything.

# **To Reproduce**
*Steps to reproduce the behavior:*
1. Go to: https://beta.portal.aws.biochemistry.gwu.edu/account
2. Click on: Groups dropdown
3. Click on 'Add Groups' Button
4. Nothing happens 

# **Expected behavior**
*A clear and concise description of what you expected to happen.*

I expected the 'Add Groups' button to take me somewhere where I can add search for additional groups, or add groups based on some sort of invite code.

# **Screenshots**
*If applicable, add screenshots to help explain your problem.*

![image](https://user-images.githubusercontent.com/73913404/122966540-7399b200-d357-11eb-8e49-b9e70f2b32ed.png)

# **Desktop (please complete the following information):**
 - OS: **Windows10**
 - Browser: **Chrome**

# **Additional context**
*Add any other context about the problem here.*

N/A

**Comment by jpat1546** [comment]
Removing from milestone- would require completely new set of pages be added. Don't have bandwidth for this release.
