### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by klangstonn23** [biocompute-objects/portal#47]
# **Describe the bug**
*A clear and concise description of what the bug is.*

When trying to add the reviewers name, the page goes completely white. This was fixed once I chose approved as the status

# **To Reproduce**
*Steps to reproduce the behavior:*

1. Go to 'add reviewer'
2. Click on 'name'
3. Type 'name'

# **Expected behavior**
*A clear and concise description of what you expected to happen.*

page goes white and BCO is erased

# **Screenshots**

# **Desktop (please complete the following information):**

 - OS: ***[Mac Computer]***
 - Browser  ***[Chome]***

# **Additional context**

***[ADD ANY ADDITONAL INFORMATION YOU FEEL WASN'T INCLUDED ABOVE. PUT N/A IF THERE IS NONE]***
N/A

**Comment by HadleyKing** [comment]
@klangstonn23 
Thanks for the issue report. This has been scheduled to be addressed in the next release.

**Comment by kee007ney** [comment]
Another user added a recording of the issue:
https://youtu.be/O6wMvaQCUe0

**Comment by HadleyKing** [comment]
Fixed with #55
