### ISSUE TITLE
Cannot save Account Details or Add Group

### ISSUE THREAD

**Issue by sfenste** [biocompute-objects/portal#48]
# **Describe the bug**
*A clear and concise description of what the bug is.*

***Cannot Save Account Details or Add group***

# **To Reproduce**
*literally just go to builder and try:*

***[EXAMPLE STEP TEMPLATE BELOW: FILL IN INFO AND ADD/REMOVE STEPS AS NEEDED]***

# **Expected behavior**
*A clear and concise description of what you expected to happen.*

***[REPLACE WITH THE BEHAVIOR YOU EXPECTED. PUT N/A IF YOU ARE UNSURE.]***

# **Screenshots**

***[PASTE IMAGE HERE. OPTIONALLY ADD DESCRIPTION]***

# **Desktop (please complete the following information):**

 - OS: ***[REPLACE WITH YOUR OPERATING SYSTEM: e.g. Windows10]***
 - Browser  ***[REPLACE WITH THE BROWSER YOU ACCESSED THE PORTAL ON: e.g. Chome, Firefox]***

# **Additional context**

***[ADD ANY ADDITONAL INFORMATION YOU FEEL WASN'T INCLUDED ABOVE. PUT N/A IF THERE IS NONE]***

**Comment by HadleyKing** [comment]
@sfenste 
Thanks for the issue report. This is a known issue we have planned to fix in the next release.
