### ISSUE TITLE
Issue accessing my BCO drafts and saving

### ISSUE THREAD

**Issue by TIHroh** [biocompute-objects/portal#52]
# **Issues viewing draft and saving it**
Recently, when I try to save my draft on the BCOdb server, I am unable to find it on the BCO portal. I was able to save my previous drafts on the BCOdb server though. In addition, I can view the published BCOs when I go to BioCompute Objects but somehow I am unable to view the drafts. I can still login in on the BCO portal though so I am not sure what is going on*

***[ BUG DESCRIPTION]***

# **Attempts to save and view draft**
*:*

 **

1. After entering info on Builder scrolled up to Draft Sharing and Publishing '...'
2. Click on arrow tab next to it '....'
3. Scrolled down to save draft and selected  ' Bco drafters...' for server under Save Draft
4. Went to BioCompute Objects to look for drafts but unable to see them. When I click on my previous drafts, I cannot view them but can view the published ones.

# **Expected behavior**
*I was hoping that I could view my drafts once I selected the server but something must have occurred during the time I made my drafts and saved them.*

# [**Screenshots**]
 1) 
![Pic1](https://user-images.githubusercontent.com/90285402/134430971-80ca114e-3677-4970-97e7-3d451edede31.PNG)

2) BCO 2021 HepC Sample Virus (RH) Can't find file for draft I recently clicked save for under Builder. Was able to find my previously saved drafts under the Objects tab though. When I click on their Accession numbers, however, all it pops up is a blank page. 

 
![Pic2](https://user-images.githubusercontent.com/90285402/134431691-1f5c314d-391c-4ba4-a336-86200857a1fe.PNG)
# **Desktop (please complete the following information):**
 - OS: ***[Windows10]***
 - Browser  ***Internet Explorer***

# **Additional context**
When I click on account, I have one for bco_drafters under the Server info and three other listed as anon for tokens. I think something may have happened like getting logged out of my account when I did not know it while working on my drafts at some point.
 
***[ADD ANY ADDITONAL INFORMATION YOU FEEL WASN'T INCLUDED ABOVE. PUT N/A IF THERE IS NONE]**
![Pic3](https://user-images.githubusercontent.com/90285402/134431891-4a322987-5594-460d-9a75-eb1a86483180.PNG)
*
@HadleyKing

**Comment by jpat1546** [comment]
Resolved in last update. Thank you.
