### ISSUE TITLE
Description Domain "Show Prereqs/Input/Output" Error

### ISSUE THREAD

**Issue by kmartinez834** [biocompute-objects/portal#53]
# **Describe the bug**

Under Description Domain, upon clicking on a dropdown menu (Show Prerequisites/Show Inputs/Show Outputs), no text can be added to the fields. If user types in any field other than URI, the screen goes white.

# **To Reproduce**

1. Go to Description Domain
2. Click on Show Prerequisites or Show Inputs or Show Outputs
3. Type in URI box
4. No text is added
5. Type in any other box
6. Screen goes white

# **Expected behavior**

Expected to be able to paste a URI and add a description

# **Screenshots**

![Screen Shot 2021-09-23 at 11 47 08 PM](https://user-images.githubusercontent.com/90285371/134615420-b921d2d0-e2c5-4551-b3ad-2d294016b2ea.png)

# **Desktop (please complete the following information):**

 - OS: MacOS Catalina Version 10.15.7
 - Browser  Chrome

# **Additional context**

***[ADD ANY ADDITONAL INFORMATION YOU FEEL WASN'T INCLUDED ABOVE. PUT N/A IF THERE IS NONE]***

**Comment by HadleyKing** [comment]
Fixed with 79aa810318f158312f8829aeeb2816795f8cd393
