### ISSUE TITLE
1. Go to 'Account'

### ISSUE THREAD

**Issue by JordanVollenweider** [biocompute-objects/portal#56]
# **Describe the bug**
*A clear and concise description of what the bug is.*

***[REPLACE WITH BUG DESCRIPTION]***

# **To Reproduce**
*Steps to reproduce the behavior:*

***[EXAMPLE STEP TEMPLATE BELOW: FILL IN INFO AND ADD/REMOVE STEPS AS NEEDED]***

# **Expected behavior**
*A clear and concise description of what you expected to happen.*

***[REPLACE WITH THE BEHAVIOR YOU EXPECTED. PUT N/A IF YOU ARE UNSURE.]***

# **Screenshots**

***[PASTE IMAGE HERE. OPTIONALLY ADD DESCRIPTION]***

# **Desktop (please complete the following information):**

 - OS: ***[REPLACE WITH YOUR OPERATING SYSTEM: e.g. Windows10]***
 - Browser  ***[REPLACE WITH THE BROWSER YOU ACCESSED THE PORTAL ON: e.g. Chome, Firefox]***

# **Additional context**

***[ADD ANY ADDITONAL INFORMATION YOU FEEL WASN'T INCLUDED ABOVE. PUT N/A IF THERE IS NONE]***

**Comment by JordanVollenweider** [comment]
1. Go to 'Account'

**Comment by HadleyKing** [comment]
JordanVollenweider Thanks for reporting this. This behavior was reported already in issue #48 and will be addressed in the next release.

**Comment by HadleyKing** [comment]
@JordanVollenweider  Thanks for reporting this. This behavior was reported already in issue #48 and will be addressed in the next release.
