### ISSUE TITLE
BioCompute Services

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/portal#66]
Page needs to be created/updated
Original content at https://github.com/biocompute-objects/bco-public-website/blob/main/content/services.md

**Comment by HadleyKing** [comment]
Card/page has been hidden for the 4.0.0 release. Should be addressed in a later release.

**Comment by jpat1546** [comment]
deadline: 3.5.22

**Comment by jpat1546** [comment]
https://github.com/biocompute-objects/BCO_Specification/blob/main/content/services_WIP

**Comment by jpat1546** [comment]
md [here](https://github.com/biocompute-objects/BCO_Specification/blob/main/content/services.md) 

Revisit "Services" as team-- confirm we're able to continue with those listed and brainstorm several others that would provide value to organizations we're looking to partner with or adopt BCO. Then modify page and push it live.
