### ISSUE TITLE
Leadership

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/portal#67]
Page needs to be created/updated
@jpat1546 the content for this page is at https://github.com/biocompute-objects/bco-public-website/blob/main/content/leadership.md

**Comment by jpat1546** [comment]
https://github.com/biocompute-objects/BCO_Specification/blob/main/content/leadership.md wip

**Comment by jpat1546** [comment]
markdown [here ](https://github.com/biocompute-objects/BCO_Specification/blob/main/content/leadership.md). 

Need to reconvene the committee- revisit + map out BioCompute short term and long term objectives. Confirm membership. Then modify [leadership](https://github.com/biocompute-objects/BCO_Specification/blob/main/content/leadership.md) page and push them live. Reopen this issue then.
