### ISSUE TITLE
Couldn't review the BCO objects

### ISSUE THREAD

**Issue by Zhe-Yu-2021** [biocompute-objects/portal#73]
# **Describe the bug**
*A clear and concise description of what the bug is.*

***[The BioCompute object list did not show up when clicking the "BioCompute Objects" button. But if I log out, I can see the list of published BCO]***

# **To Reproduce**
*Steps to reproduce the behavior:*

***[EXAMPLE STEP TEMPLATE BELOW: FILL IN INFO AND ADD/REMOVE STEPS AS NEEDED]***

1. Go to 'https://biocomputeobject.org/objects'
2. Click on 'BioCompute Object'
3. See "Loading...", 

# **Expected behavior**
*The list of all published and drafted BCO *

# **Screenshots**

***[
![image](https://user-images.githubusercontent.com/90285351/138518442-7b858e02-d557-4ee4-8d44-7ba5463b2e1f.png)
]***

# **Desktop (please complete the following information):**

 - OS: ***[REPLACE WITH YOUR OPERATING SYSTEM: e.g. Windows10]***
 - Browser  ***[Chrome and Microsoft edge]***

**Comment by HadleyKing** [comment]
Fixed with 79aa810318f158312f8829aeeb2816795f8cd393
