### ISSUE TITLE
URI problem in the description domain

### ISSUE THREAD

**Issue by Zhe-Yu-2021** [biocompute-objects/portal#74]
# **Describe the bug**
* Whatever I put in the URI of "show prerequisites", the "show output" URI will have the same thing, and vice versa. Please see the screenshot*

***[REPLACE WITH BUG DESCRIPTION]***

# **To Reproduce**
*Steps to reproduce the behavior:*

***[EXAMPLE STEP TEMPLATE BELOW: FILL IN INFO AND ADD/REMOVE STEPS AS NEEDED]***

# **Expected behavior**
*A clear and concise description of what you expected to happen.*

***[REPLACE WITH THE BEHAVIOR YOU EXPECTED. PUT N/A IF YOU ARE UNSURE.]***

# **Screenshots**

***[
![image](https://user-images.githubusercontent.com/90285351/138929213-5eb6482f-1494-44b0-bf39-a4adf99b95d9.png)
]***

# **Desktop (please complete the following information):**

 - OS: ***[REPLACE WITH YOUR OPERATING SYSTEM: e.g. Windows10]***
 - Browser  ***[REPLACE WITH THE BROWSER YOU ACCESSED THE PORTAL ON: e.g. Chome, Firefox]***

# **Additional context**

***[ADD ANY ADDITONAL INFORMATION YOU FEEL WASN'T INCLUDED ABOVE. PUT N/A IF THERE IS NONE]***

**Comment by HadleyKing** [comment]
Fixed with 79aa810318f158312f8829aeeb2816795f8cd393
