### ISSUE TITLE
Object page will not load without token

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/portal#8]
Object page wont load for non-logged in users.

<img width="678" alt="Screen Shot 2021-05-26 at 8 47 26 AM" src="https://user-images.githubusercontent.com/20343214/119662423-5d074600-bdff-11eb-9495-792570cb19ac.png">

**Comment by carmstrong1gw** [comment]
Create view similar to existing published object retrieval which gets **all** published objects.
