### ISSUE TITLE
BCO_067092/1.0 Page fails to load

### ISSUE THREAD

**Issue by Rosswell** [biocompute-objects/portal#96]
# **Describe the bug**
*A clear and concise description of what the bug is.*

When navigating to https://www.biocomputeobject.org/objects/view/https/biocomputeobject.org/BCO_067092/1.0 on 

- safari v15.2
- firefox v95.0.2
- chrome v96.0.4664.110

the page does not load. The console shows the following error:
```
TypeError: null is not an object (evaluating 'o.apiinfo')
```

# **To Reproduce**
*Steps to reproduce the behavior:*

1. Go to https://www.biocomputeobject.org/objects/view/https/biocomputeobject.org/BCO_067092/1.0
2. Note that the page doesn't load
3. Open devtools console

# **Expected behavior**
*A clear and concise description of what you expected to happen.*

page does indeed load

# **Screenshots**

![image](https://user-images.githubusercontent.com/24869120/147724779-be1e315b-d785-4789-9be5-d15f4d73cfac.png)

# **Desktop (please complete the following information):**

 - OS: MacOS Monterey v12.1
 - Browser: safari v15.2 / firefox v95.0.2 / chrome v96.0.4664.110

# **Additional context**

N/A

**Comment by HadleyKing** [comment]
@Rosswell 
Thanks for the detailed bug report! We have pushed a patch for this issue.
